# Base image with Java 21
FROM eclipse-temurin:21

# Set working directory
WORKDIR /app

# Copy the JAR file generated by Maven
COPY target/*.jar app.jar

# Expose application port
EXPOSE 8080

# Start the application
ENTRYPOINT ["java", "-jar", "app.jar"]